name: Unzip and Commit

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install unzip

      - name: Unzip file
        run: |
          unzip StreamSanctum_Project.zip -d extracted_files
          rm StreamSanctum_Project.zip

      - name: Move files
        run: |
          mv extracted_files/* ./
          rm -r extracted_files

      - name: Commit unzipped content
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped project files"
          git push
